= https://github.com/input-output-hk/cardano-node-emulator[Cardano Node Emulator]
:email: plutus@iohk.io
:author: Input Output HK Limited
:toc: left
:reproducible:

image:https://img.shields.io/badge/policy-Cardano%20Engineering%20Handbook-informational[link=https://input-output-hk.github.io/cardano-engineering-handbook]

== Introduction

TODO

[[Architecture]]
== Architecture

The repository consists of a set of components:

- link:./cardano-node-emulator[cardano-node-emulator]

== Development

[[how-to-develop]]
=== How to develop and contribute to the project

Run `nix develop` to enter the development shell and you will be presented with a list of available commands.

**Please see link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING] for comprehensive documentation on how to contribute to the project, including development and submitting changes*

== Running tests

The emulator includes several test suites; the `plutus-ledger` package already
contains property and unit tests, and the `cardano-node-emulator` library has an
`emulator-test` suite added in 1.4.1 which exercises the transaction
validation logic.

You can run the tests in one of two ways:

* **Nix shell** (preferred):

```sh
nix develop          # drops you into a shell with GHC/Cabal available
cabal test emulator-test
```

* **Standalone Cabal**: install `cabal-install` on your system (`sudo apt
  install cabal-install` on Ubuntu, or `ghcup` on other platforms) and then
run the same `cabal` commands above from the project root.

The `emulator-test` verifies that transactions containing duplicate inputs are
rejected; see the documentation link below for details of this red‑team fix.

== Documentation

* link:doc/duplicate-input-validation.adoc[Duplicate-input validation bug and fix]


=== User documentation

User documentations are work in progress. You may generate Haskell API documentation (haddocks) directly from `nix develop` for each of the components:

```
cabal haddock cardano-node-emulator
```

== Working with the project

=== How to submit an issue

Issues can be filed in the https://github.com/input-output-hk/cardano-node-emulator/issues[GitHub Issue tracker].

However, note that this is pre-release software, so we will not usually be providing support.

[[how-to-develop]]
=== How to develop and contribute to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING], which describes our processes in more detail including development environments; and <<Architecture>>, which describes the structure of the repository.

== Licensing

You are free to copy, modify, and distribute the Cardano Node Emulator Library under the terms of the Apache 2.0 license. See the link:./LICENSE[LICENSE] and link:./NOTICE[NOTICE] files for details.
