= https://github.com/input-output-hk/cardano-node-emulator[Cardano Node Emulator]
:email: plutus@iohk.io
:author: Input Output HK Limited
:toc: left
:reproducible:

image:https://img.shields.io/badge/policy-Cardano%20Engineering%20Handbook-informational[link=https://input-output-hk.github.io/cardano-engineering-handbook]

== Introduction

TODO

[[Architecture]]
== Architecture

The repository consists of a set of components:

- link:./cardano-node-emulator[cardano-node-emulator]

== Development

[[how-to-develop]]
=== How to develop and contribute to the project

Run `nix develop` to enter the development shell and you will be presented with a list of available commands.

**Please see link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING] for comprehensive documentation on how to contribute to the project, including development and submitting changes*

== Documentation

=== User documentation

User documentations are work in progress. You may generate Haskell API documentation (haddocks) directly from `nix develop` for each of the components:

```
cabal haddock cardano-node-emulator
```

== Working with the project

=== How to submit an issue

Issues can be filed in the https://github.com/input-output-hk/cardano-node-emulator/issues[GitHub Issue tracker].

However, note that this is pre-release software, so we will not usually be providing support.

[[how-to-develop]]
=== How to develop and contribute to the project

See link:CONTRIBUTING{outfilesuffix}[CONTRIBUTING], which describes our processes in more detail including development environments; and <<Architecture>>, which describes the structure of the repository.

== Licensing

You are free to copy, modify, and distribute the Cardano Node Emulator Library under the terms of the Apache 2.0 license. See the link:./LICENSE[LICENSE] and link:./NOTICE[NOTICE] files for details.
