spec-version: 0.36.0
name: plutus-script-utils
version: 2.0.1.0
license: Apache-2.0
license-file:
  - LICENSE
  - NOTICE
language: Haskell2010
default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveAnyClass
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveLift
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - EmptyDataDeriving
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - ImportQualifiedPost
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - PolyKinds
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - ViewPatterns
ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wnoncanonical-monad-instances
  - -Wno-unused-packages
  - -Wredundant-constraints
  - -Widentities
  - -Wmissing-import-lists
  - -Wno-missed-extra-shared-lib
  - -fobject-code
  - -fno-ignore-interface-pragmas
  - -fignore-hpc-changes
  - -fno-omit-interface-pragmas
  - -fplugin-opt
  - PlutusTx.Plugin:target-version=1.1.0
  - -fplugin-opt
  - PlutusTx.Plugin:defer-errors
  - -fplugin-opt
  - PlutusTx.Plugin:conservative-optimisation

library:
  source-dirs: src
  exposed-modules:
    - Plutus.Script.Utils.Address
    - Plutus.Script.Utils.Data
    - Plutus.Script.Utils.Scripts
    - Plutus.Script.Utils.V1
    - Plutus.Script.Utils.V1.Contexts
    - Plutus.Script.Utils.V1.Generators
    - Plutus.Script.Utils.V1.Scripts
    - Plutus.Script.Utils.V1.Typed
    - Plutus.Script.Utils.V2
    - Plutus.Script.Utils.V2.Contexts
    - Plutus.Script.Utils.V2.Generators
    - Plutus.Script.Utils.V2.Scripts
    - Plutus.Script.Utils.V2.Typed
    - Plutus.Script.Utils.V3
    - Plutus.Script.Utils.V3.Contexts
    - Plutus.Script.Utils.V3.Generators
    - Plutus.Script.Utils.V3.Typed
    - Plutus.Script.Utils.Value
    - Prettyprinter.Extras
  dependencies:
    - aeson
    - base >=4.9 && <5
    - bytestring
    - cardano-api
    - cardano-ledger-core
    - data-default
    - mtl
    - plutus-core
    - plutus-ledger-api
    - plutus-tx
    - plutus-tx-plugin
    - prettyprinter
    - serialise
    - tagged
  when:
    - condition: "!((impl(ghc >= 9.6) && impl(ghc < 9.7)) || (impl(ghc >= 9.12) && impl(ghc < 9.13)))"
      buildable: false
